---

- name: Deploy app
  hosts: app

  tasks:
  - name: Install git
    become: true
    package:
      name: git
      state: present

  - name: Fetch the latest version of application code
    git:
      repo: 'https://github.com/express42/reddit.git'
      dest: /home/ubuntu/reddit
      version: monolith

  - name: Bundle install
    bundler:
      state: present
      chdir: /home/ubuntu/reddit
