---

- name: Deploy app
  hosts: app

  tasks:
  - name: Install git
    become: true
    package:
      name: git
      state: present

  - name: Fetch the latest version of application code
    git:
      repo: 'https://github.com/express42/reddit.git'
      dest: "/home/{{deploy_user}}/reddit"
      version: monolith
    notify: Restart puma

  - name: Bundle install
    bundler:
      state: present
      chdir: "/home/{{deploy_user}}/reddit"
    notify: Restart puma

  handlers:
  - name: Restart puma
    become: yes
    systemd:
      name: puma
      state: restarted
