---

- name: Install mongodb
  hosts: all
  become: yes
  tasks:

  - name: Add repo key
    apt_key:
      url: "https://www.mongodb.org/static/pgp/server-4.2.asc"
      state: present

  - name: Add repo
    apt_repository:
      repo: "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.2 multiverse"
      filename: "mongodb-org-4.2"
      update_cache: yes
      state: present

  - name: Install mongodb-org
    apt:
      name: "mongodb-org"
      update_cache: no
      state: present

  - name: Enable mongod
    service:
      name: "mongod"
      enabled: yes
