---

- name: Configure MongoDB
  hosts: db
  vars:
    mongo_bind_ip: 0.0.0.0
  become: true
  tags: db-tag

  tasks:
  - name: Change mongo config file
    template:
      src: templates/mongod.conf.j2
      dest: /etc/mongod.conf
      mode: 0644
    notify: restart mongod

  handlers:
  - name: restart mongod
    service: name=mongod state=restarted

- name: Deploy app
  hosts: app
  tags: deploy-tag

  tasks:
  - name: Install git
    become: true
    package:
      name: git
      state: present

  - name: Fetch the latest version of application code
    git:
      repo: 'https://github.com/express42/reddit.git'
      dest: /home/ubuntu/reddit
      version: monolith
    notify: reload puma

  - name: Bundle install
    bundler:
      state: present
      chdir: /home/ubuntu/reddit

  handlers:
  - name: reload puma
    systemd: name=puma state=restarted

- name: Configure app
  hosts: app
  vars:
    db_host: 192.168.10.23
  become: true
  tags: app-tag

  tasks:
  - name: Add unit file for Puma
    copy:
      src: files/puma.service
      dest: /etc/systemd/system/puma.service
      mode: 0644
    notify: reload puma

  - name: Add config for DB connection
    template:
      src: templates/db_config.j2
      dest: /home/ubuntu/db_config
      owner: ubuntu
      group: ubuntu
      mode: 0644

  - name: enable puma
    systemd: name=puma enabled=yes

  handlers:
  - name: reload puma
    systemd: name=puma state=restarted
