---

name: Validate Packer, Terraform & Ansible

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  validate_packer:
    runs-on: ubuntu-latest
    name: Validate Packer

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Fix Template
      uses: hashicorp/packer-github-actions@master
      with:
        command: fix
        target: packer/app.json packer/db.json

    - name: Validate Template
      uses: hashicorp/packer-github-actions@master
      with:
        command: validate
        arguments: -syntax-only
        target: packer/app.json packer/db.json

  validate_terraform_stage:
    runs-on: ubuntu-latest
    name: Validate Terraform Stage

    defaults:
      run:
        working-directory: terraform/stage/

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.12.31

    - name: Terraform fmt
      run: terraform fmt -check
      continue-on-error: true

    - name: Terraform Init
      run: terraform init -backend=false

    - name: Terraform Validate
      run: terraform validate -no-color

  validate_terraform_prod:
    runs-on: ubuntu-latest
    name: Validate Terraform Prod

    defaults:
      run:
        working-directory: terraform/prod/

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.12.31

    - name: Terraform fmt
      run: terraform fmt -check
      continue-on-error: true

    - name: Terraform Init
      run: terraform init -backend=false

    - name: Terraform Validate
      run: terraform validate -no-color

  validate_ansible:
    runs-on: ubuntu-latest
    name: Validate Ansible

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Lint Ansible Playbooks
      uses: ansible/ansible-lint-action@master
      with:
        targets: "ansible/playbooks/*.yml"
        args: "-c ./ansible/.ansible-lint"
